name: faceswap_camera
description: "FaceSwap iVCam-like camera streaming app with real-time face swap"
publish_to: 'none'
version: 1.4.0+7

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  web_socket_channel: ^2.4.0
  permission_handler: ^11.3.0
  wakelock_plus: ^1.1.4
  shared_preferences: ^2.2.2
  http: ^1.2.0
  flutter_webrtc: ^1.2.0
  image_picker: ^1.1.2
  image: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
